export const Amenities = [
    "Dual Key",
    "Penthouse",
    "Original Condition",
    "Renovated",
    "Low Floor",
    "Mid Floor",
    "High Floor",
    "Top Floor",
    "Corner Unit",
    "Ground Floor",
    "Function Room",
    "Multi-purpose Hall",
    "Meeting Rooms",
    "Study Room",
    "Children's Playground",
    "Squash Court",
    "Mini Golf Range",
    "Mini-mart",
    "Dining Room Furniture",
    "Lounge",
    "Barbeque Pits (BBQ)",
    "Clubhouse",
    "Hammocks",
    "Mini-mart",
    "Gymnasium Room",
    "Amphitheatre",
    "Outdoor Patio",
    "Private Garden",
    "Private Pool",
    "Roof Terrace",
    "Open Terrace",
    "Retail Shops",
    "Poolside Lounge",
    "Meeting Room",
    "Games Room",
    "Karaoke",
    "Library",
    "Spa Pavilion",
    "Pavilion",
    "Lounge",
    "Adventure Park",
    "Billiards Room",
    "Swimming Pool",
    "Fun Pool",
    "Lap Pool",
    "Aerobic Pool",
    "Infinity Pool",
    "Leisure Pool",
    "Jet Pool",
    "Spa Pool",
    "Rooftop Pool",
    "Wading Pool",
    "Pool Deck",
    "Waterfall",
    "Water Feature",
    "Water Channel",
    "Fountain",
    "Tennis Court",
    "Badminton Court",
    "Basketball Court",
    "Fitness Corner",
    "Jogging Track",
    "Reflexology Path",
    "Hydrotherapy Pool",
    "Yoga Corner",
    "Squash Court",
    "Underwater Fitness Station",
    "Bowling Alley",
    "Aerobic Pool",
    "Fibre Ready",
    "Wireless Internet",
    "Broadband Internet",
    "Internet Connection",
    "Cat 5 Cabling",
    "Cat 5/6 Cabling",
    "Dual Power Source",
    "Dual Telecom Risers",
    "ISDN",
    "Videoconferencing",
    "AV Equipment",
    "24-Hour Access",
    "24 hours security",
    "CCTV Security",
    "Security Access Control",
    "Turnstile System",
    "Stove",
    "Oven / Microwave",
    "Dishwasher",
    "Fridge",
    "Washing Machine",
    "Dryer",
    "Kitchen Utensils",
    "Launderette",
    "Pantry",
    "Water Heater",
    "Grease Trap",
    "Jacuzzi",
    "Hammocks",
    "Sky Lounge",
    "Sky Terrace",
    "Spa Pavilion",
    "Wine and Cigar Room",
    "City View",
    "Sea View",
    "Pool View",
    "Lake View",
    "Greenery View",
    "Park / Greenery View",
    "Covered Car Park",
    "Basement Car Park",
    "Multi-Storey Car Park",
    "Car Parking",
    "Meeting Rooms",
    "Function Room",
    "Large Floor Plate",
    "Large Floor Plates",
    "Raised Access Floor",
    "Server Room",
    "Concierge",
    "Secretarial Services",
    "Reception Services",
    "Sofa",
    "Bed",
    "Dining Room Furniture",
    "Couch",
    "Closet",
    "Walk-in-wardrobe",
    "Community Garden",
    "Barbeque Pits",
    "Amphitheatre",
    "Viewing Deck",
    "Outdoor Dining",
    "Community Plaza",
    "Bomb Shelter",
    "Maids Room",
    "Maid Room",
    "Backup Generator",
    "Chilled Water Supply",
    "Hairdryer",
    "Iron / Ironing Board",
    "Water Trap",
    "Utility Room",
    "Restrooms"
];

// export const Amenities = {
//     "Residential Living & Accommodation": [
//       "Dual Key",
//       "Penthouse",
//       "Original Condition",
//       "Renovated",
//       "Low Floor",
//       "Mid Floor",
//       "High Floor",
//       "Top Floor",
//       "Corner Unit",
//       "Ground Floor"
//     ],
//     "Rooms & Spaces": [
//       "Function Room",
//       "Multi-purpose Hall",
//       "Meeting Rooms",
//       "Study Room",
//       "Children's Playground",
//       "Squash Court",
//       "Mini Golf Range",
//       "Mini-mart",
//       "Dining Room Furniture",
//       "Lounge",
//       "Barbeque Pits (BBQ)",
//       "Clubhouse",
//       "Hammocks",
//       "Mini-mart",
//       "Gymnasium Room",
//       "Amphitheatre",
//       "Outdoor Patio",
//       "Private Garden",
//       "Private Pool",
//       "Roof Terrace",
//       "Open Terrace",
//       "Retail Shops",
//       "Poolside Lounge",
//       "Meeting Room",
//       "Games Room",
//       "Karaoke",
//       "Library",
//       "Spa Pavilion",
//       "Pavilion",
//       "Lounge",
//       "Adventure Park",
//       "Billiards Room"
//     ],
//     "Swimming Pools & Water Features": [
//       "Swimming Pool",
//       "Fun Pool",
//       "Lap Pool",
//       "Aerobic Pool",
//       "Infinity Pool",
//       "Leisure Pool",
//       "Jet Pool",
//       "Spa Pool",
//       "Rooftop Pool",
//       "Wading Pool",
//       "Pool Deck",
//       "Waterfall",
//       "Water Feature",
//       "Water Channel",
//       "Fountain"
//     ],
//     "Sports & Fitness": [
//       "Tennis Court",
//       "Badminton Court",
//       "Basketball Court",
//       "Fitness Corner",
//       "Jogging Track",
//       "Reflexology Path",
//       "Hydrotherapy Pool",
//       "Yoga Corner",
//       "Squash Court",
//       "Underwater Fitness Station",
//       "Bowling Alley",
//       "Aerobic Pool"
//     ],
//     "Technology & Connectivity": [
//       "Fibre Ready",
//       "Wireless Internet",
//       "Broadband Internet",
//       "Internet Connection",
//       "Cat 5 Cabling",
//       "Cat 5/6 Cabling",
//       "Dual Power Source",
//       "Dual Telecom Risers",
//       "ISDN",
//       "Videoconferencing",
//       "AV Equipment"
//     ],
//     "Security & Access": [
//       "24-Hour Access",
//       "24 hours security",
//       "CCTV Security",
//       "Security Access Control",
//       "Turnstile System"
//     ],
//     "Kitchen & Laundry": [
//       "Stove",
//       "Oven / Microwave",
//       "Dishwasher",
//       "Fridge",
//       "Washing Machine",
//       "Dryer",
//       "Kitchen Utensils",
//       "Launderette",
//       "Pantry",
//       "Water Heater",
//       "Grease Trap"
//     ],
//     "Luxury Features": [
//       "Jacuzzi",
//       "Hammocks",
//       "Sky Lounge",
//       "Sky Terrace",
//       "Spa Pavilion",
//       "Wine and Cigar Room"
//     ],
//     "Views": [
//       "City View",
//       "Sea View",
//       "Pool View",
//       "Lake View",
//       "Greenery View",
//       "Park / Greenery View"
//     ],
//     "Parking & Transport": [
//       "Covered Car Park",
//       "Basement Car Park",
//       "Multi-Storey Car Park",
//       "Car Parking"
//     ],
//     "Office & Business Support": [
//       "Meeting Rooms",
//       "Function Room",
//       "Large Floor Plate",
//       "Large Floor Plates",
//       "Raised Access Floor",
//       "Server Room",
//       "Concierge",
//       "Secretarial Services",
//       "Reception Services"
//     ],
//     "Furniture & Fixtures": [
//       "Sofa",
//       "Bed",
//       "Dining Room Furniture",
//       "Couch",
//       "Closet",
//       "Walk-in-wardrobe"
//     ],
//     "Outdoor Amenities": [
//       "Community Garden",
//       "Barbeque Pits",
//       "Amphitheatre",
//       "Viewing Deck",
//       "Outdoor Dining",
//       "Community Plaza"
//     ],
//     "Miscellaneous": [
//       "Bomb Shelter",
//       "Maids Room",
//       "Maid Room",
//       "Backup Generator",
//       "Chilled Water Supply",
//       "Hairdryer",
//       "Iron / Ironing Board",
//       "Water Trap",
//       "Utility Room",
//       "Restrooms"
//     ]
//   };
  