export const Districts = [
  { value: "D01", label: "D01 (Boat Quay / Raffles Place / Marina)" },
  { value: "D02", label: "D02 (Chinatown / Tanjong Pagar)" },
  { value: "D03", label: "D03 (Alexandra / Commonwealth)" },
  { value: "D04", label: "D04 (Harbourfront / Telok Blangah)" },
  { value: "D05", label: "D05 (Buona Vista / West Coast / Clementi New Town)" },
  { value: "D06", label: "D06 (City Hall / Clarke Quay)" },
  { value: "D07", label: "D07 (Beach Road / Bugis / Rochor)" },
  { value: "D08", label: "D08 (Farrer Park / Serangoon Rd)" },
  { value: "D09", label: "D09 (Orchard / River Valley)" },
  { value: "D10", label: "D10 (Tanglin / Holland / Bukit Timah)" },
  { value: "D11", label: "D11 (Newton / Novena)" },
  { value: "D12", label: "D12 (Balestier / Toa Payoh)" },
  { value: "D13", label: "D13 (Macpherson / Potong Pasir)" },
  { value: "D14", label: "D14 (Eunos / Geylang / Paya Lebar)" },
  { value: "D15", label: "D15 (East Coast / Marine Parade)" },
  { value: "D16", label: "D16 (Bedok / Upper East Coast)" },
  { value: "D17", label: "D17 (Changi Airport / Changi Village)" },
  { value: "D18", label: "D18 (Pasir Ris / Tampines)" },
  { value: "D19", label: "D19 (Hougang / Punggol / Sengkang)" },
  { value: "D20", label: "D20 (Ang Mo Kio / Bishan / Thomson)" },
  { value: "D21", label: "D21 (Clementi Park / Upper Bukit Timah)" },
  { value: "D22", label: "D22 (Boon Lay / Jurong / Tuas)" },
  { value: "D23", label: "D23 (Dairy Farm / Bukit Panjang / Choa Chu Kang)" },
  { value: "D24", label: "D24 (Lim Chu Kang / Tengah)" },
  { value: "D25", label: "D25 (Admiralty / Woodlands)" },
  { value: "D26", label: "D26 (Mandai / Upper Thomson)" },
  { value: "D27", label: "D27 (Sembawang / Yishun)" },
  { value: "D28", label: "D28 (Seletar / Yio Chu Kang)" },
];
export const Districts_Arr = {
  D01: ["Boat Quay", "Raffles Place", "Marina"],
  D02: ["Chinatown", "Tanjong Pagar"],
  D03: ["Alexandra", "Commonwealth"],
  D04: ["Harbourfront", "Telok Blangah"],
  D05: ["Buona Vista", "West Coast", "Clementi New Town"],
  D06: ["City Hall", "Clarke Quay"],
  D07: ["Beach Road", "Bugis", "Rochor"],
  D08: ["Farrer Park", "Serangoon Rd"],
  D09: ["Orchard", "River Valley"],
  D10: ["Tanglin", "Holland", "Bukit Timah"],
  D11: ["Newton", "Novena"],
  D12: ["Balestier", "Toa Payoh"],
  D13: ["Macpherson", "Potong Pasir"],
  D14: ["Eunos", "Geylang", "Paya Lebar"],
  D15: ["East Coast", "Marine Parade"],
  D16: ["Bedok", "Upper East Coast"],
  D17: ["Changi Airport", "Changi Village"],
  D18: ["Pasir Ris", "Tampines"],
  D19: ["Hougang", "Punggol", "Sengkang"],
  D20: ["Ang Mo Kio", "Bishan", "Thomson"],
  D21: ["Clementi Park", "Upper Bukit Timah"],
  D22: ["Boon Lay", "Jurong", "Tuas"],
  D23: ["Dairy Farm", "Bukit Panjang", "Choa Chu Kang"],
  D24: ["Lim Chu Kang", "Tengah"],
  D25: ["Admiralty", "Woodlands"],
  D26: ["Mandai", "Upper Thomson"],
  D27: ["Sembawang", "Yishun"],
  D28: ["Seletar", "Yio Chu Kang"],
};
