export const MrtGroups = {
    North: [
      "Admiralty MRT",
      "Canberra MRT",
      "Khatib MRT",
      "Woodlands MRT",
      "Woodlands North MRT",
      "Woodlands South MRT",
      "Yio Chu Kang MRT",
      "Yishun MRT",
      "Lentor MRT",
      "Springleaf MRT",
      "Sembawang MRT",
      "Kranji MRT"
    ],
    East: [
      "Bedok MRT",
      "Bedok North MRT",
      "Bedok Reservoir MRT",
      "Bedok South MRT",
      "Changi Airport MRT",
      "Elias MRT",
      "Eunos MRT",
      "Geylang Bahru MRT",
      "Kaki Bukit MRT",
      "Marine Parade MRT",
      "Marine Terrace MRT",
      "Siglap MRT",
      "Pasir Ris MRT",
      "Pasir Ris East MRT",
      "Simei MRT",
      "Tampines MRT",
      "Tampines North MRT",
      "Tampines East MRT",
      "Tampines West MRT",
      "Upper Changi MRT",
      "Tanjong Rhu MRT",
      "Tanjong Katong MRT"
    ],
    West: [
      "Bahar Junction MRT",
      "Boon Lay MRT",
      "Bukit Batok MRT",
      "Bukit Batok West MRT",
      "Bukit Gombak MRT",
      "Bukit Panjang MRT",
      "Cashew MRT",
      "Chinese Garden MRT",
      "Choa Chu Kang MRT",
      "Choa Chu Kang West MRT",
      "Clementi MRT",
      "Dover MRT",
      "Hong Kah MRT",
      "Jurong East MRT",
      "Jurong West MRT",
      "Jurong Lake District MRT",
      "Lakeside MRT",
      "Pandan Reservoir MRT",
      "Tengah Park MRT",
      "Tengah Plantation MRT",
      "Toh Guan MRT",
      "West Coast MRT"
    ],
    Central: [
      "Ang Mo Kio MRT",
      "Bishan MRT",
      "Botanic Gardens MRT",
      "Braddell MRT",
      "Bukit Timah MRT",
      "Caldecott MRT",
      "City Hall MRT",
      "Dhoby Ghaut MRT",
      "Esplanade MRT",
      "Farrer Park MRT",
      "Farrer Road MRT",
      "HarbourFront MRT",
      "Havelock MRT",
      "Holland Village MRT",
      "Little India MRT",
      "Lorong Chuan MRT",
      "Marina Bay MRT",
      "Marymount MRT",
      "Maxwell MRT",
      "Novena MRT",
      "Orchard MRT",
      "Orchard Boulevard MRT",
      "Queenstown MRT",
      "Redhill MRT",
      "Raffles Place MRT",
      "Somerset MRT",
      "Stevens MRT",
      "Toa Payoh MRT"
    ],
    NorthEast: [
      "Buangkok MRT",
      "Defu MRT",
      "Hougang MRT",
      "Kovan MRT",
      "Punggol MRT",
      "Punggol Point LRT",
      "Rivervale LRT",
      "Seng Kang MRT",
      "Serangoon MRT",
      "Sengkang MRT",
      "Tongkang LRT",
      "Sumang LRT"
    ],
    LRT: [
      "Bakau LRT",
      "Bangkit LRT",
      "Cheng Lim LRT",
      "Compassvale LRT",
      "Cove LRT",
      "Damai LRT",
      "Farmway LRT",
      "Fajar LRT",
      "Fernvale LRT",
      "Jelapang LRT",
      "Kangkar LRT",
      "Keat Hong LRT",
      "Kupang LRT",
      "Layar LRT",
      "Meridian LRT",
      "Nibong LRT",
      "Petir LRT",
      "Phoenix LRT",
      "Ranggung LRT",
      "Rumbia LRT",
      "Senja LRT",
      "Segar LRT",
      "Soo Teck LRT",
      "South View LRT",
      "Teck Whye LRT",
      "Thanggam LRT"
    ]
  };
  